<?php

return [
    'agenda_items' => [
        'CALL TO ORDER AND RELATED BUSINESS',
        'COUNCILLOR INQUIRIES',
        'Councillor Inquiries',
        'RESPONSES TO COUNCILLOR INQUIRIES',
        'RESPONSES TO COUNCILLOR INQUIRES',
        'RESPONSES TO COUNCILLOR INQUIRIES - NONE',
        'REPORTS TO BE DEALT WITH AT A FUTURE MEETING - NONE',
        'REPORTS TO BE DEALT WITH AT A FUTURE MEETING',
        'REPORT TO BE DEALT WITH AT A FUTURE MEETING - NONE',
        'REPORTS TO BE DEALT WITH AT A FUTURE MEETING - NONE REPORTS POSTPONED BY AGENDA REVIEW COMMITTEE',
        'REPORTS TO BE DEALT WITH AT A FUTURE MEETING - NONE REPORTS RE-ROUTED BY AGENDA REVIEW COMMITTEE',
        'STATUS REPORT',
        'STATUS REPORT - NONE',
        'STATUS REPORTS - NONE',
        'REPORTS',
        'REPORTS - NONE',
        'BYLAWS',
        'BYLAWS AND RELATED REPORTS - 1:30 P.M.',
        'BYLAWS AND RELATED REPORTS - 3:45 P.M.',
        'MOTIONS PENDING',
        'PRIVATE REPORTS',
        'PRIVATE REPORTS - NONE',
        'NOTICES OF MOTION AND MOTIONS WITHOUT CUSTOMARY NOTICE',
        'CALL TO ORDER',
        'ADOPTION OF AGENDA',
        'Adoption of Minutes',
        'Protocol Items',
        'ITEMS FOR DISCUSSION AND RELATED BUSINESS',
        'Select Items for Debate',
        'Vote on Bylaws not Selected for Debate',
        'Requests to Speak',
        'Requests for Specific Time on Agenda',
        'EXPLANATION OF PUBLIC HEARING PROCESS',
        'Call for Persons to Speak',
        'ADJOURNMENT',
        'BYLAWS AND RELATED REPORTS - 2 P.M.'
    ]
];
